pipeline:
  build-and-release:
    image: gcc:latest
    commands:
      # Dipendenze e compilazione Linux
      - apt-get update && apt-get install -y cmake libsdl2-dev mingw-w64
      - mkdir build_linux && cd build_linux
      - cmake ..
      - cmake --build . --config Release
      - cd ..
      
      # Cross-compilazione Windows (.exe)
      - mkdir build_win && cd build_win
      - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/win_toolchain.cmake ..
      - cmake --build .
      - mv MiaApp.exe MiaApp-Windows.exe
      - cd ..

      # Creazione Release automatica su Codeberg
      - plugin: gitea-release
        settings:
          base_url: https://codeberg.org
          files:
            - build_linux/MiaApp
            - build_win/MiaApp-Windows.exe
          api_key:
            from_secret: codeberg_token
    when:
      event: tag
