pipeline:
  build-linux:
    image: archlinux:latest
    commands:
      - pacman-key --init
      - pacman-key --populate archlinux
      - pacman -Sy --noconfirm git base-devel cmake sdl2
      - mkdir build_linux && cd build_linux
      - cmake -DCMAKE_BUILD_TYPE=Release ..
      - make -j$(nproc)

  build-windows:
    image: archlinux:latest
    commands:
      - pacman-key --init
      - pacman-key --populate archlinux
      - pacman -Sy --noconfirm git base-devel cmake mingw-w64-gcc mingw-w64-sdl2
      - mkdir build_win && cd build_win
      - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/win_toolchain.cmake -DCMAKE_BUILD_TYPE=Release ..
      - make -j$(nproc)
      - cp /usr/x86_64-w64-mingw32/bin/SDL2.dll .
